# Site settings
title: Marcelo Boeira - Site Reliability Engineer
email: me@marceloboeira.com
description: "Site Reliability Engineer - Berlin, Germany"
url: "https://marceloboeira.com/"
markdown: kramdown
permalink: pretty
