# Site settings
title: Marcelo Boeira
email: me@marceloboeira.com
description: "Marcelo Boeira - Solutions Architect @ AWS - Berlin, Germany"
url: "https://marceloboeira.com/"
markdown: kramdown
permalink: pretty
