# Site settings
title: Marcelo Boeira
email: contact@marceloboeira.com
description: "This is my personal website, make with Jekyll and hosted at Github.cm"
baseurl: ""
url: "http://new.marceloboeira.com/"


bitbucket-url: http://bucket.marceloboeira.com
skype-url: callTo://boeiraexe
linkedin-url: http://br.linkedin.com/in/marceloboeira
instagram-url: http://instagram.com/marceloboeirajr
github-user: marceloboeira
github-url: http://github.com/
facebook-user: b03ir4
facebook-url: http://fb.me/
twitter-user: b03ir4
twitter-url: http://twitter.com/




# Build settings
markdown: kramdown
permalink: pretty
