# Site settings
title: Marcelo Boeira - Software Engineer
email: me@marceloboeira.com
description: "Software Engineer living in Berlin, Germany"
url: "https://marceloboeira.com/"

markdown: kramdown
permalink: pretty
