# Site settings
title: Marcelo Boeira - Senior Platform Engineer @ heycar
email: me@marceloboeira.com
description: "Platform Engineer living in Berlin, Germany"
url: "http://marceloboeira.com/"

markdown: kramdown
permalink: pretty
