# Site settings
title: Marcelo Boeira
email: me@marceloboeira.com
description: "Marcelo Boeira - Site Reliability Engineer - Berlin, Germany"
url: "https://marceloboeira.com/"
markdown: kramdown
permalink: pretty
