# Site settings
title: Marcelo Boeira
email: me@marceloboeira.com
description: "This is my personal website, make with Jekyll and hosted at Github.com"
baseurl: ""
url: "http://new.marceloboeira.com/"

markdown: kramdown
permalink: pretty
